### ISSUE TITLE
Change Scala Stream Collector port from 80 to 8080

### ISSUE THREAD

**Issue by Seltsamsel** [snowplow/snowplow-docker#124]
I'm trying to run the Scala Stream Collector (Kinesis) version 0.15.0, but I get the error message:
`docker run -v /path/to/stream/collector/config:/snowplow/config --env-file ../environment snowplow-docker-registry.bintray.io/snowplow/scala-stream-collector-kinesis:0.15.0 --config /snowplow/config/application.conf`
> [scala-stream-collector-akka.actor.default-dispatcher-3] ERROR com.snowplowanalytics.snowplow.collectors.scalastream.KinesisCollector$ - REST interface could not be bound to 0.0.0.0:80

I guess the reason is, that the user inside the docker image is a regular user, which has no permissions to listen on ports lower than 1024. This should apply to the other Stream Collectors, too.

You could probably just listen on port 8080 and forward it to port 80 in the `docker run` command. But maybe I miss something, since your examples don't forward any ports to the Docker instance at all?

**Comment by BenFradet** [comment]
Hey, internally we only use 8080.

It's true that the readme example could use an update or we could alternatively make port 80 available.

PRs are welcome :+1:
