### ISSUE TITLE
Add support for beam-enrich CLI params in k8s-dataflow

### ISSUE THREAD

**Issue by peel** [snowplow/snowplow-docker#137]

**Comment by chuwy** [comment]
Its not only beam-enrich. BQ Loader will also use the same parameters.

**Comment by chuwy** [comment]
Oh, I thought you meant labels.

**Comment by peel** [comment]
Nope, this is strictly about being able to reuse beam-enrich's CLI params for graceful shutdown if for some reason bucket for dataflow job has not been created/removed.

edit: https://github.com/snowplow-incubator/snowplow-google-cloud-storage-loader/issues/36

**Comment by chuwy** [comment]
Are we sure it cannot happen for BQ Loader job?
