### ISSUE TITLE
Provide a Docker Compose example

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-docker#15]
with a minimal set of functionalities:

- collector
- stream enrich
- ~~kafka~~
- s3-loader
- es-loader

**Comment by alexanderdean** [comment]
Kafka is orthogonal to the other 2 bullet points - I would suggest we do:

* `docker-compose-kinesis`
* `docker-compose-kafka`

We shouldn't be responsible for spinning up Kafka itself in the `docker-compose-kafka` example.

**Comment by BenFradet** [comment]
The great thing if we were to have Kafka in the example is that it would become a turnkey solution, everything is ready to go, just need to send some example events.

**Comment by alexanderdean** [comment]
Sure - but I don't want us to stray into supporting a blessed Kafka deployment. The release is the easy bit - the ongoing support commitment is what I want to avoid.
