### ISSUE TITLE
Add CI/CD to deploy all images into our Bintray

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-docker#16]

**Comment by BenFradet** [comment]
for future references: https://bintray.com/docs/usermanual/formats/formats_dockerrepositories.html

**Comment by BenFradet** [comment]
should we also push to docker hub? I didn't find a mirroring mechanism in bintray

**Comment by alexanderdean** [comment]
Potentially - let's create a separate unscheduled ticket to consider that
