### ISSUE TITLE
Add Dockerfile for RDB Loader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-docker#17]
Unscheduled as there's still some work to do around how the RDB Loader is deployed.

**Comment by c4l3b** [comment]
Hi - do you have an estimate on when this task will be completed? I noticed it was removed from all the milestone releases.

**Comment by BenFradet** [comment]
It's not on the short term plan at the moment unfortunately

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/snowplow-rdb-loader/issues/172
