### ISSUE TITLE
Ensure the JVM process adheres to CPU and memory limits imposed by Docker

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-docker#21]
https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

**Comment by BenFradet** [comment]
In our case this is just of matter of setting `-XX:+UnlockExperimentalVMOptions` and 
`-XX:+UseCGroupMemoryLimitForHeap`.

>As of Java SE 8u131, and in JDK 9, the JVM is Docker-aware with respect to Docker CPU limits transparently.

and the `openjdk:8-jre-alpine` image is based on 8u131.
