### ISSUE TITLE
Install LZO as part of the S3 Loader image

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-docker#23]
LZO is not part of the base alpine install and is not installed by default since it's not necessary for gzip.

Priority was given to image size over supporting all functionalities, this needs to be reversed.

**Comment by alexanderdean** [comment]
Can you add a description?

**Comment by alexanderdean** [comment]
Why wouldn't we install this automatically in the Docker image for the S3 Loader? This feels like actually a great use case for using Docker with a JVM app.

**Comment by BenFradet** [comment]
The reasoning was: because it's only needed for a subset of cases and we want to keep the image size as small as possible.

**Comment by alexanderdean** [comment]
It's required for core functionality in the S3 Loader, to the extent that it's even listed in the README:

https://github.com/snowplow/snowplow-s3-loader#prerequisites

I am re-filing this as a bug that support for this wasn't added in the R1.

**Comment by traroe** [comment]
I see you have created a pull request for this.  Do you have an estimated timeline for when you might have the updated Docker images in the repo?

**Comment by BenFradet** [comment]
The release will most likely coincide with [R96](https://github.com/snowplow/snowplow/pull/3489) which shouldn't be too far out.

However, the next couple of weeks will be quite loaded so I can't promise anything.

**Comment by traroe** [comment]
👍  Thanks!  I'm in the process of developing helm charts for a kubernetes deploy of snowplow, and I was trying to determine if I should build my own image, or if I could be lazy. :-D

**Comment by BenFradet** [comment]
the "build your own image" route shouldn't be too time-consuming: you can just inherit the current image and additionally install the lzo package for alpine.

**Comment by traroe** [comment]
Yeah, it's a simple change, but pulling an image from a public registry into kubernetes is quite a bit easier versus a private one.  Again, lazy. =)  Thanks again!
