### ISSUE TITLE
Replace default --usage flag by --help

### ISSUE THREAD

**Issue by rbolkey** [snowplow/snowplow-docker#26]
This could be an issue with either the stream collector or the Dockerfile, but `--usage` is an unknown option to the stream collector.

https://github.com/snowplow/snowplow-docker/blob/a20fbfdbbf24a0414d6ae728fb5921cdfcb7bb58/scala-stream-collector/0.10.0/Dockerfile#L26

**Comment by rbolkey** [comment]
But looks like it does support a `--help` flag.

**Comment by alexanderdean** [comment]
Is there a commit for this?

**Comment by BenFradet** [comment]
not yet no
