### ISSUE TITLE
Which stream collector image to use for stdout as a sink?

### ISSUE THREAD

**Issue by rbolkey** [snowplow/snowplow-docker#54]
It looks like the packaging as of 0.13.0 limits to a particular sink, and I'm not able to configure the existing ones to use stdout as the sink.

**Comment by BenFradet** [comment]
hey @rbolkey , since the stdout sink's main purpose is debugging, the jar is not published and so there is no associated docker image.

**Comment by alexanderdean** [comment]
Should we add it?

**Comment by rbolkey** [comment]
I would find it useful. Even if it is just for debugging; most external users are likely debugging configuration and not really needing or wanting to rebuild binaries from source.

I may be a special case though since I'm interested in using `stdout` to explore a custom pipeline that would provide a mechanism to release back pressure.

**Comment by rbolkey** [comment]
I haven't checked for a while, but looks like there are images on docker hub for this now, closing:

https://hub.docker.com/r/snowplow/scala-stream-collector-stdout
