### ISSUE TITLE
Fix DB race condition in example of Iglu server

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/snowplow-docker#60]
One important thing that went unnoticed is that although `depends_on` adjust start order of services, it is possible that iglu server will try to connect to postgres before `init.sql` is run. Since `init.sql` initializes user and database to be used by Iglu Server, that possibility will end up with connection error to postgres.

One solution is to wait until postgres is "fully ready to be used", meaning that a successful connection can be performed using credentials in `init.sql`.

I noticed this during development of sp mini 0.6.0 and integrated above solution into sp mini, which can be easily applied to here as well.

**Comment by chuwy** [comment]
Postgres container in `docker-compose up -d` now fails with following logs:

```
FATAL:  "/var/lib/postgresql/data" is not a valid data directory
DETAIL:  File "/var/lib/postgresql/data/PG_VERSION" does not contain valid data.
HINT:  You might need to initdb.
```

Previous version works fine.

**Comment by BenFradet** [comment]
reopening and reverting, @oguzhanunlu could you take care of this?

**Comment by oguzhanunlu** [comment]
Sure @BenFradet and thanks for the report @chuwy , I haven't encountered this but I'll try to reproduce and debug it.

**Comment by oguzhanunlu** [comment]
Hey @chuwy , can you tell me how you used this example? I can't reproduce the issue.

I deleted `postgres:9.5` and `snowplow-docker-registry.bintray.io/snowplow/iglu-server:0.3.0` images, then I fired `docker-compose up -d` under `snowplow-docker/iglu-server/example`. I check logs through `docker logs postgres` and `docker logs iglu-server` .

Could it be related to broken postgres container left from a previous usage? Or an issue with docker engine on your machine or mine? I couldn't observe this in a fresh vagrant machine either.

**Comment by chuwy** [comment]
Indeed, after removing existing `postgres` image it works. But is it expected behavior? Without this script `postgres` image does not affect server start.
