### ISSUE TITLE
Add Dockerfile for Stream Enrich

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-docker#7]

**Comment by joshuacox** [comment]
https://hub.docker.com/r/webhostingcoopteam/snowplow-emretlrunner/   I have a dockerized emretlrunner that I have been working on before finding this repo.  I'm very sad to see this repo empty and would love to contribute to it.

**Comment by alexanderdean** [comment]
Contributions welcome @joshuacox ! We should be getting to this in a week or two, so the timing is good...
