### ISSUE TITLE
Can't fork repository

### ISSUE THREAD

**Issue by danielzohar** [snowplow/snowplow-docker#8]
Seems like I cannot fork the repository. Maybe that's because there's no code checked in? Have never seen that before.

![screen shot 2016-03-16 at 16 42 09](https://cloud.githubusercontent.com/assets/6514918/13820622/1b6b7324-eb96-11e5-8bcc-e0fd0dc0300f.png)

**Comment by alexanderdean** [comment]
@jbeemster can you push something so @danielzohar can fork!

**Comment by jbeemster** [comment]
Did that fix it @danielzohar ?

**Comment by danielzohar** [comment]
yes, thanks. Will create a PR shortly

**Comment by danielzohar** [comment]
Working now
